spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resumematcher?useSSL=false&serverTimezone=UTC
    username: root
    password: Bb110500@@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
